### ISSUE TITLE
fsSize from Docker container

### ISSUE THREAD

**Issue by gallofeliz** [sebhildebrandt/systeminformation#804]
**Is your feature request related to a problem? Please describe.**

Hello, I am migrating from Telegraf to own nodejs solution. I run systeminformation in a docker container (all my applications are in Docker).

For Telegraph, with help of its documentation, I had the docker-compose :

```
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf.d:/etc/telegraf/telegraf.d:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
```

I tried to do the same with systeminformation, but fsSize returns [] (empty array).

**Describe the solution you'd like**

I'd like to do like Telegraf, mount my root host fs into a docker container folder and systeminformation would be able to give me informations about it (free size, total size, used size at minimum, read/write stats if possible) 

**Describe alternatives you've considered**

If not possible, I will make my own exec() but am I alone ? Should be good to support systeminformation in docker container.

**Additional context**

No

Regards
